name: Deploy Static Website

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Adjust as needed

      # Step 3: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust region as needed

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 6: Sync Static Files to S3
      - name: Sync Files to S3
        run: |
          aws s3 sync ./src s3://potfolio19122024 --delete
